export const ELECTION_DETAILS_REQUEST = "ELECTION_DETAILS_REQUEST";
export const ELECTION_DETAILS_SUCCESS = "ELECTION_DETAILS_SUCCESS";
export const ELECTION_DETAILS_FAIL = "ELECTION_DETAILS_FAIL";
export const ELECTION_DETAILS_RESET = "ELECTION_DETAILS_RESET";

export const ELECTION_LIST_REQUEST = "ELECTION_LIST_REQUEST";
export const ELECTION_LIST_SUCCESS = "ELECTION_LIST_SUCCESS";
export const ELECTION_LIST_FAIL = "ELECTION_LIST_FAIL";
