export const WALLET_DETAILS_REQUEST = "WALLET_DETAILS_REQUEST";
export const WALLET_DETAILS_SUCCESS = "WALLET_DETAILS_SUCCESS";
export const WALLET_DETAILS_FAIL = "WALLET_DETAILS_FAIL";
export const WALLET_DETAILS_RESET = "WALLET_DETAILS_RESET";
